first_site/cricket/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('scorecard/',views.scorecard,name='scorecard'),
]

first_site/first_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('cricket/',include("cricket.urls")),
]

first_site/hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sayhello', views.say_hello, name='say_hello'),
    path('rps/direct/<str:user_choice>', views.play_rps, name='play_rps'),
    path('rps/form', views.show_rps_form, name='show_rps_form'),
    path('rps/processform', views.process_rps_form, name='process_rps_form'),
    path('rps/resetwins', views.reset_win_counts, name='reset_wins')
]

first_site/cricket/models.py
from django.db import models

class Team(models.Model):
    name = models.CharField(max_length=100)

    def _str_(self):
        return self.name

class Player(models.Model):
    name = models.CharField(max_length=100)
    runs = models.IntegerField()
    balls_faced = models.IntegerField()
    fours = models.IntegerField()
    sixes = models.IntegerField()
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def _str_(self):
        return self.name

first_site/hello/models.py
from django.db import models

# Create your models here.

first_site/cricket/views.py
from django.shortcuts import render
from .models import Team, Player
from django.db import models


def scorecard(request):
    teams = Team.objects.all()

    for team in teams:
        # Calculate team score
        team_score = Player.objects.filter(team=team).aggregate(total_score=models.Sum('runs'))
        team.score = team_score['total_score']

        # Calculate number of wickets
        team_wickets = Player.objects.filter(team=team).count()
        team.wickets = team_wickets

    context = {
        'teams': teams
    }

    return render(request, 'cricket/first.html', context)

first_site/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse
import random
# Create your views here.

R_P_S = ["rock", "paper", "scissors"]

def computer_guess() -> str:
    return random.choice(R_P_S)

def play_rock_paper_scissors(p1: str, p2: str) -> str:
    if p1.lower() == p2.lower():
        return "draw", "draw"
    outcomes = {("rock", "paper"): "paper",
                ("scissors", "paper"): "scissors",
                ("scissors", "rock"): "rock"}
    inputs = (max(p1, p2), min(p1, p2))
    outcome = outcomes[inputs]
    winner = 'p1' if p1 == outcome else 'p2'
    return winner, outcome

def say_hello(request):
    return HttpResponse('''
    <!doctype html>
    <html>
        <body>
            <h3>Greetings</h3>
            <p>Hello, World!</p>
        </body>
    </html>''')

def play_rps(request, user_choice):
    #user_choice = request.GET['user_choice']
    #user_choice = request.GET.get('user_choice', 'rock')
    computer_choice = computer_guess()
    outcome = play_rock_paper_scissors(user_choice, computer_choice)
    context = {"user": user_choice,
               "computer": computer_choice,
               "outcome": outcome}
    return render(request, "hello/rps.html", context)

def show_rps_form(request):
    return render(request, "hello/rps_form.html")

def process_rps_form(request):
    user_choice = request.POST['user_choice']
    computer_choice = computer_guess()
    winner, outcome = play_rock_paper_scissors(user_choice, computer_choice)
    if request.session.get('user_wins') is None:
        request.session['user_wins'] = 0
    if request.session.get('computer_wins') is None:
        request.session['computer_wins'] = 0
    if winner == 'p1':
        request.session['user_wins'] += 1
    elif winner == 'p2':
        request.session['computer_wins'] += 1
    context = {"user": user_choice,
               "computer": computer_choice,
               "outcome": outcome}
    return render(request, "hello/rps.html", context)

def reset_win_counts(request):
    print(all([ch in 'abcde' for ch in 'abf']))
    request.session['user_wins'] = 0
    request.session['computer_wins'] = 0
    return render(request, "hello/rps_form.html")

first_site/cricket/templates/cricket/first.html
<!DOCTYPE html>
<html>
<head>
    <title>Cricket Scorecard</title>
</head>
<body>
    <h1>Cricket Scorecard</h1>

    {% for team in teams %}
        <h2>{{ team.name }} - Score: {{ team.score }}/{{ team.wickets }}</h2>
        <table>
            <thead>
                <tr>
                    <th>Player</th>
                    <th>Runs</th>
                    <th>Balls Faced</th>
                    <th>4's</th>
                    <th>6's</th>
                </tr>
            </thead>
            <tbody>
                {% for player in team.player_set.all %}
                    <tr>
                        <td>{{ player.name }}</td>
                        <td>{{ player.runs }}</td>
                        <td>{{ player.balls_faced }}</td>
                        <td>{{ player.fours }}</td>
                        <td>{{ player.sixes }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endfor %}
</body>
</html>

first_site/hello/templates/hello/rps.html
<!doctype HTML>
<html>
    <body>
        <h3>Rock-Paper-Scissors</h3>
        <p>User: {{request.session.user_wins}} 
            Computer: {{request.session.computer_wins}}</p>
        <form action="{% url 'process_rps_form' %}" method="post">
            {% csrf_token %}
            <label for="user_choice">Choose</label>
            <input type="text" id="user_choice" name="user_choice">
            <input type="submit" value="Play!">
        </form>
        <p><a href="{% url 'reset_wins' %}">Reset Scores</a></p>
    </body>
</html>

first_site/hello/templates/hello/rps_form.html
<!doctype html>
    <html>
        <body>
            <h3>Rock-Paper-Scissors</h3>
            <p>User: {{request.session.user_wins}} 
            Computer: {{request.session.computer_wins}}</p>
            <p>You Chose {{user}}</p>
            <p>Computer chose {{computer}}</p>
            <p>Winner: {{outcome}}</p>
            <a href="{% url 'show_rps_form' %}">Play Again</a>
            <a href="{% url 'reset_wins' %}">Reset Scores</a>
        </body>
    </html>